### ISSUE TITLE
Suggestion: Add suspend-on-demand

### ISSUE THREAD

**Issue by sbrl** [Hau-Hau/firefox-tab-suspender#10]
It's possible that this idea might be better implemented in a separate extension, but I'd love to be able to right click on a tab and hit "suspend" manually.

To that end, I'd like to disable the automatic suspend feature too.

**Comment by eggsyntax** [comment]
I'll second the idea of suspending a tab manually -- that's something I really miss from The Great Suspender on on Chrome. I think it actually has much *higher* value than on Chrome, because you can't kill a single tab in Firefox, and you don't always want to close all suspected runaways, but suspending them would let you find the problem one while not losing your other tabs.

Thanks for firefox-tab-suspender!

**Comment by Hau-Hau** [comment]
Hello!

I always had these features in plans but your and other people's suggestions convinced me to change priority of tasks. 
After that when I finish latest very important task (non-native discarding), i will be doing task's FTS-5 -> FTS-4 -> FTS-2 ([roadmap](https://trello.com/b/BbbjVfl4/firefox-tab-suspender-public))
Every of these tasks are connected so this order is most optimal.

Thanks for support,
Michalewicz Piotr

**Comment by ProgrammingLife** [comment]
Disabling automatic suspend and manual suspending features would be awesome! Can't wait these feature to come.

**Comment by Hau-Hau** [comment]
Hello!

Disabling automatic suspend and manual suspending is released (v. 3.3.0)!
Happy testing!

Best regards,
Michalewicz Piotr

**Comment by eggsyntax** [comment]
That's really fantastic -- talk about response time! Thank you so much for addressing this so quickly :smile: :pray:

**Comment by eggsyntax** [comment]
I'm happy as a clam now that it has this feature, but if you're actively looking for other stuff to work on, one other feature that would be phenomenal would be having a whitelist of domains/urls to never suspend -- either by adding them to the whitelist manually, or (ideally) making that one of the drop-down options when right-clicking the tab.

But that's just since you asked; I'm just thrilled you added manual suspension! Thanks again :)

**Comment by sbrl** [comment]
Shall I close this issue?

**Comment by Hau-Hau** [comment]
Thanks guys for support, I will close that issue.

Cheers!
Michalewicz  Piotr
